### ISSUE TITLE
Fix Puppet 5 warnings

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icinga-vagrant#132]
- puppet-icinga2 needs Puppet 5 support
- git subtree should include reverse dependencies of those modules (many of them are optional, Puppet still doesn't like it)

```
==> icinga2: Warning: ModuleLoader: module 'timezone' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
==> icinga2:    (file & line not available)
==> icinga2: Notice: Scope(Class[Selinux::Config]): A reboot is required to fully disable SELinux. SELinux will operate in Permissive mode until a reboot
==> icinga2: Warning: ModuleLoader: module 'mysql' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
==> icinga2:    (file & line not available)
==> icinga2: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> icinga2:                     with Pattern[]. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/icinga2/manifests/init.pp", 158]:
==> icinga2:    (at /tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> icinga2: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> icinga2:                     with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/icinga2/manifests/init.pp", 160]:
==> icinga2:    (at /tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> icinga2: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> icinga2:                     with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/icinga2/manifests/init.pp", 164]:
==> icinga2:    (at /tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> icinga2: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> icinga2:                     with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/icinga2/manifests/init.pp", 166]:
==> icinga2:    (at /tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> icinga2: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Bool instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/icinga2/manifests/init.pp", 171]:
==> icinga2:    (at /tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> icinga2: Warning: This method is deprecated, please use match expressions with Stdlib::Compat::String instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/icinga2/manifests/init.pp", 173]:
==> icinga2:    (at /tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> icinga2: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> icinga2:                     with Stdlib::Compat::Absolute_Path. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/icinga2/manifests/feature/mainlog.pp", 38]:["/tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/icinga2/manifests/init.pp", 199]
==> icinga2:    (at /tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> icinga2: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> icinga2:                     with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/icinga2/manifests/feature/idomysql.pp", 180]:
==> icinga2:    (at /tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> icinga2: Warning: This method is deprecated, please use the stdlib validate_legacy function,
==> icinga2:                     with Stdlib::Compat::Integer. There is further documentation for validate_legacy function in the README. at ["/tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/icinga2/manifests/feature/idomysql.pp", 181]:
==> icinga2:    (at /tmp/vagrant-puppet/modules-a4064da9dc5ceed3d5e73cff001d6777/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
==> icinga2: Warning: ModuleLoader: module 'php' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
==> icinga2:    (file & line not available)
==> icinga2: Warning: The function 'hiera_hash' is deprecated in favor of using 'lookup'. See https://docs.puppet.com/puppet/4.10/reference/deprecated_language.html
==> icinga2:    (file & line not available)
==> icinga2: Warning: ModuleLoader: module 'icingaweb2' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
==> icinga2:    (file & line not available)
```

**Comment by dnsmichi** [comment]
I'm waiting for v2.0 released later this year.
